apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespaceName | default .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  serviceName: {{ .Chart.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql.secretName" . }}
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql.secretName" . }}
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql.secretName" . }}
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: app_db
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
              subPath: mysql
            - name: config-map
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
      volumes:
        - name: config-map
          configMap:
            name: {{ include "mysql.configMapName" . }}
      tolerations:
        - key: {{ .Values.toleration.key | quote }}
          operator: {{ .Values.toleration.operator | quote }}
          value: {{ .Values.toleration.value | quote }}
          effect: {{ .Values.toleration.effect | quote }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: {{ .Values.affinity.podAntiAffinityLabelKey | quote }}
                    operator: In
                    values:
{{- range .Values.affinity.podAntiAffinityLabelValues }}
                      - {{ . | quote }}
{{- end }}
              topologyKey: {{ .Values.affinity.topologyKey | quote }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.affinity.nodeAffinityKey | quote }}
                    operator: In
                    values:
{{- range .Values.affinity.nodeAffinityValues }}
                      - {{ . | quote }}
{{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.pvc.requestsStorage }}

