apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.clusterIP.name }}
  namespace: {{ .Values.namespaceName | default .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.clusterIP.port }}
      targetPort: {{ .Values.service.clusterIP.targetPort }}

